services:

  web:
    image: fitter73/nginx-php:1.0
    ports:
      - "80:80"

    #php
  app:
    image: fitter73/php-composer:1.0
    environment:
      MYSQL_HOST: db  # service name
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      REDIS_HOST: cache
      REDIS_PORT: ${REDIS_PORT}
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  db:
    image: mysql:8.0
    volumes:
      - mysqldata:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}


  cache:
    image: redis:latest

volumes:
  mysqldata:


